language: node_js
node_js:
  - 0.11
env:
  global:
    - PROTRACTOR_BROWSERS=firefox
    - KARMA_BROWSERS=Firefox,PhantomJS

install:
  - npm install

before_script:
  - npm install -g phantomjs
  - npm install -g protractor
  - webdriver-manager update
  - webdriver-manager start &
    - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - python -m SimpleHTTPServer 3000 &


script:
  - npm test
